### ISSUE TITLE
Partials gets added to collections

### ISSUE THREAD

**Issue by NVolcz** [GrimLink/eleventy-plugin-sass#1]
Noticed that the scss partials was added to my sitemap.xml.
I am using the canary release of Eleventy.

My `sitemap.njk`:
```
---
permalink: /sitemap.xml
eleventyExcludeFromCollections: true
---
<?xml version="1.0" encoding="utf-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    {% for page in collections.all %}
        <url>
            <loc>{{ site.url }}{{ page.url | url }}</loc>
            <lastmod>{{ page.date.toISOString() }}</lastmod>
        </url>
    {% endfor %}
</urlset>
```

One solution is to add an `getData` function to the `addExtension` object:
```
getData: async function(inputPath) {
    let parsed = path.parse(inputPath);
    if (parsed.name.startsWith("_")) return {eleventyExcludeFromCollections: true};
    return {};
},
```

**Comment by GrimLink** [comment]
@NVolcz thank you for the issue, I will checkout and create a fix, probably your suggestion as it looks good.
If you want you can also create the pull request 😉

**Comment by GrimLink** [comment]
@NVolcz again thank you, I was not aware of this issue.
I made a fix with @allrude.

The CSS generated with this plugin will now never show up in the collections.

**Comment by NVolcz** [comment]
Thanks for being so responsive (way faster than I am) and for fixing the issue. Love the plugin!
